- name: enable dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ CA_DIR }}"
  - "{{ BASE_DIR }}/roles/init/files"

- name: copy cfssl tools
  copy: src={{ BASE_DIR }}/bin/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: copy ca-config.json
  template: src=ca-config.json.j2 dest={{ CA_DIR }}/ca-config.json

- name: copy ca-csr.json
  template: src=ca-csr.json.j2 dest={{ CA_DIR }}/ca-csr.json

- name: generate CA certs
  shell: "cd {{ CA_DIR }} && {{ BIN_DIR }}/cfssl gencert -initca ca-csr.json | {{ BIN_DIR }}/cfssljson -bare ca"

- name: copy CA from {{ CA_DIR }} to {{ BASE_DIR }}/roles/init/files
  copy: src={{ CA_DIR }}/{{ item }} dest={{ BASE_DIR }}/roles/init/files/{{ item }} force=no
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json
