- name: enable addon dirs
  file: name={{ item }} state=directory
  with_items:
  - /root/local/addons/nginx-ingress

- name: distribute cm yaml
  template: src=configmap.yaml.j2 dest=/root/local/addons/nginx-ingress/configmap.yaml

- name: distribute cm yaml
  template: src=tcp-services-configmap.yaml.j2 dest=/root/local/addons/nginx-ingress/tcp-services-configmap.yaml

- name: distribute cm yaml
  template: src=udp-services-configmap.yaml.j2 dest=/root/local/addons/nginx-ingress/udp-services-configmap.yaml

- name: distribute ns yaml
  template: src=namespace.yaml.j2 dest=/root/local/addons/nginx-ingress/namespace.yaml

- name: distribute backend yaml
  template: src=default-backend.yaml.j2 dest=/root/local/addons/nginx-ingress/default-backend.yaml

- name: distribute rbac yaml
  template: src=rbac.yaml.j2 dest=/root/local/addons/nginx-ingress/rbac.yaml

- name: distribute deploy yaml
  template: src=with-rbac.yaml.j2 dest=/root/local/addons/nginx-ingress/with-rbac.yaml

- name: start dashboard
  shell: "{{ bin_dir }}/kubectl create -f /root/local/addons/nginx-ingress/ && sleep 15"
  when: NODE_ID is defined and NODE_ID == "node1"
  ignore_errors: true
